version: "3.9"

services:
  frontend:
    image: nginx:<choose latest but lightweight version>
    container_name: <provide any frontend name>
    ports:
      - "<provide any unused host port>:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - <backend service name>
    networks:
      - <network name>

  backend:
    build: ./backend
    container_name: <provide any backend name> 
    environment:
      - DB_URL=mongodb://database:27017/mydb
    ports:
      - "<provide any unused host port>:3000"
    depends_on:
      - <database service name>
    networks:
      - <network name>

  database:
    image: mongo:6
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<provide DB User name>
      - MONGO_INITDB_ROOT_PASSWORD=<provide DB Password>
    volumes:
      - <volume name>:/data/db
    ports:
      - "<provide any unused host port>:27017"
    networks:
      - <network name>

networks:
  <network name>:

volumes:
  <volume name>:
